name: Pipeline con Seguridad

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

      #  MALA PRÁCTICA (NO HACER)
      - name: Login inseguro
        run: echo "password=123456"

      #  BUENA PRÁCTICA (SECRETS)
      - name: Uso seguro
        run: echo " Token cargado correctamente"
        env:
          TOKEN: ${{ secrets.TOKEN_API }}
