name: Pipeline con Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    #  Paso 3 — Añadir entorno
    environment: production

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

      #  Paso 1 — Crear paso deploy (general)
      - name: Deploy
        run: echo "Desplegando aplicación..."

      #  Paso 2 — Solo si todo ha ido bien
      - name: Deploy producción
        if: success()
        run: echo " Deploy en producción OK"
