name: Pipeline Control Test + Deploy

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      #  TEST (NO detiene pipeline)
      - name: Ejecutar tests
        id: test_step
        run: npm test
        continue-on-error: true

      #  INFORMAR resultado del test (didáctico)
      - name: Resultado del test OK
        if: steps.test_step.outcome == 'success'
        run: echo " Tests correctos"

      - name: Resultado del test FALLIDO
        if: steps.test_step.outcome == 'failure'
        run: echo " Tests fallidos"

      #  DEPLOY SOLO SI TODO OK
      - name: Deploy producción
        if: success()
        run: echo " Deploy en producción realizado"

      #  NOTIFICACIONES
      - name: Notificación éxito
        if: success()
        run: echo " Pipeline OK"

      - name: Notificación fallo
        if: failure()
        run: echo " Pipeline con errores"
